# Drone CI File!

kind: template
load: container.jsonnet
data:
  repositoryName: josaorg/community-web
  releaseName: community-web
  buildArgs: NUXT_PUBLIC_AUTH_BASE_URL=https://community.api.prod.josa.ngo/v2/auth/
