version: "3.8"

services:

  # Nuxt Frontend
  community-web:
    container_name: community-web
    build:
      context: .
    environment:
      COMMUNITY_API_URL: http://contributions-api:8080
      PORT: 3000
      HOST: contributions-web
    ports:
      - "3000:3000"
    volumes:
      - ./:/app/

  # Nest Backend
  community-api:
    container_name: community-api
    image: josaorg/community-api:latest
    # do additional stuff here

networks:
  default:
    name: host
    external: true
