version: "3.8"

services:

  community-web:
    container_name: community-web
    image: josaorg/community-web:latest
    build:
      context: .
    # do stuff here

  community-api:
    container_name: community-api
    image: josaorg/community-api:latest
    # do additional stuff here
